# -*- coding: utf-8 -*-
"""brain_tumor_reseff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNSlZPfs6zvcvQtQREJJHrYWJ9Z4eob-
"""

import kagglehub, os, random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import ResNet50, EfficientNetB3
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

path = kagglehub.dataset_download("sartajbhuvaji/brain-tumor-classification-mri")
TRAIN_DIR = os.path.join(path, "Training")
TEST_DIR  = os.path.join(path, "Testing")
CLASS_NAMES = sorted(os.listdir(TRAIN_DIR))
print("Classes:", CLASS_NAMES)

IMG_SIZE   = (224, 224)  # Increased resolution for higher feature clarity
BATCH_SIZE = 32          # Decreased batch size slightly to accommodate larger images in GPU memory

train_gen = tf.keras.utils.image_dataset_from_directory(
    TRAIN_DIR,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

val_gen = tf.keras.utils.image_dataset_from_directory(
    TRAIN_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

test_gen = tf.keras.utils.image_dataset_from_directory(
    TEST_DIR,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=False
)

NUM_CLASSES = len(CLASS_NAMES)

# Enhanced Augmentation Layer
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.15),
])

AUTOTUNE = tf.data.AUTOTUNE
train_gen = train_gen.map(lambda x, y: (data_augmentation(x, training=True), y), num_parallel_calls=AUTOTUNE).prefetch(buffer_size=AUTOTUNE)
val_gen = val_gen.prefetch(buffer_size=AUTOTUNE)
test_gen = test_gen.prefetch(buffer_size=AUTOTUNE)

def build_resnet50():
    inputs = layers.Input(shape=(*IMG_SIZE, 3))
    preprocessed = tf.keras.applications.resnet50.preprocess_input(inputs)
    base = ResNet50(weights='imagenet', include_top=False, input_tensor=preprocessed)
    base.trainable = False
    x = base.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    out = layers.Dense(NUM_CLASSES, activation='softmax')(x)
    return Model(inputs=inputs, outputs=out, name="ResNet50")

loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1)

def build_efficientnet():
    base = EfficientNetB3(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
    base.trainable = False
    x = base.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    out = layers.Dense(NUM_CLASSES, activation='softmax')(x)
    return Model(inputs=base.input, outputs=out, name="EfficientNetB3")

callbacks = [
    EarlyStopping(patience=10, restore_best_weights=True, monitor='val_accuracy'),
    ReduceLROnPlateau(patience=2, factor=0.2, monitor='val_loss', verbose=1)
]

from sklearn.utils.class_weight import compute_class_weight
all_labels = np.concatenate([np.argmax(y, axis=1) for x, y in train_gen])
class_weights = compute_class_weight('balanced', classes=np.unique(all_labels), y=all_labels)
class_weight_dict = dict(enumerate(class_weights))
print("Class weights:", class_weight_dict)

def train_model(model):
    name = model.name
    #Warm-up
    print(f"\n{'='*50}\nPhase 1: {name} — Frozen Base (Warmup)\n{'='*50}")
    model.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])
    h1 = model.fit(train_gen, validation_data=val_gen, epochs=12,
                   callbacks=callbacks, class_weight=class_weight_dict)
    #fine-tuning
    print(f"\n{'='*50}\nPhase 2: {name} — Unfreezing Top 30 Layers\n{'='*50}")
    for layer in model.layers[-30:]:
        layer.trainable = True

    model.compile(optimizer=Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])
    h2 = model.fit(train_gen, validation_data=val_gen, epochs=10,
                   callbacks=callbacks, class_weight=class_weight_dict)   # ← add this

    merged = {}
    for k in h1.history:
        merged[k] = h1.history[k] + h2.history[k]
    return model, merged

resnet, h_resnet         = train_model(build_resnet50())
efficientnet, h_efficient = train_model(build_efficientnet())

histories = {"ResNet50": h_resnet, "EfficientNetB3": h_efficient}
models    = {"ResNet50": resnet,   "EfficientNetB3": efficientnet}

def evaluate(model, name):
    y_true = np.concatenate([y for x, y in test_gen], axis=0)
    y_true = np.argmax(y_true, axis=1)

    y_pred = np.argmax(model.predict(test_gen, verbose=0), axis=1)

    metrics = {
        "accuracy":       accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, average='macro', zero_division=0),
        "recall":    recall_score(y_true, y_pred, average='macro', zero_division=0),
        "f1":        f1_score(y_true, y_pred, average='macro', zero_division=0),
    }
    print(f"\n{'='*50}\n{name}\n{'='*50}")
    for k, v in metrics.items():
        print(f"  {k.capitalize():<10}: {v:.4f}")
    print("\n", classification_report(y_true, y_pred, target_names=CLASS_NAMES))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
    plt.title(f'Confusion Matrix — {name}')
    plt.ylabel('Actual'); plt.xlabel('Predicted')
    plt.tight_layout(); plt.show()
    return metrics

all_metrics = {name: evaluate(model, name) for name, model in models.items()}

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
for i, (name, h) in enumerate(histories.items()):
    ep = range(1, len(h['accuracy']) + 1)
    axes[i, 0].plot(ep, h['accuracy'],     label='Train'); axes[i, 0].plot(ep, h['val_accuracy'], label='Val')
    axes[i, 0].set_title(f'{name} — Accuracy'); axes[i, 0].legend()
    axes[i, 1].plot(ep, h['loss'],         label='Train'); axes[i, 1].plot(ep, h['val_loss'],     label='Val')
    axes[i, 1].set_title(f'{name} — Loss');     axes[i, 1].legend()
plt.tight_layout(); plt.show()

print(f"\n{'Model':<18} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1':>10}")
print("="*55)
for name, m in all_metrics.items():
    print(f"{name:<18} {m['acc']:>10.4f} {m['precision']:>10.4f} {m['recall']:>10.4f} {m['f1']:>10.4f}")